import Question from "@/Types/Question";

const questionList: Question[] = [
  {
    group: "have a household income over $1 million",
    actualPercent: 0,
    userGuessPercent: null,
    guessedPercent: 20,
  },
  {
    group: "are transgender",
    actualPercent: 1,
    userGuessPercent: null,
    guessedPercent: 21,
  },
  {
    group: "have a household income over $500,000",
    actualPercent: 1,
    userGuessPercent: null,
    guessedPercent: 26,
  },
  {
    group: "are Muslim",
    actualPercent: 1,
    userGuessPercent: null,
    guessedPercent: 27,
  },
  {
    group: "are Native American",
    actualPercent: 1,
    userGuessPercent: null,
    guessedPercent: 27,
  },
  {
    group: "are Jewish",
    actualPercent: 2,
    userGuessPercent: null,
    guessedPercent: 30,
  },
  {
    group: "live in New York City",
    actualPercent: 3,
    userGuessPercent: null,
    guessedPercent: 30,
  },
  {
    group: "are gay or lesbian",
    actualPercent: 3,
    userGuessPercent: null,
    guessedPercent: 30,
  },
  {
    group: "are atheists",
    actualPercent: 0,
    userGuessPercent: null,
    guessedPercent: 33,
  },
  {
    group: "are bisexual",
    actualPercent: 4,
    userGuessPercent: null,
    guessedPercent: 29,
  },
  {
    group: "are members of a union",
    actualPercent: 4,
    userGuessPercent: null,
    guessedPercent: 36,
  },
  {
    group: "are asian",
    actualPercent: 6,
    userGuessPercent: null,
    guessedPercent: 29,
  },
  {
    group: "are millitary veterans",
    actualPercent: 6,
    userGuessPercent: null,
    guessedPercent: 40,
  },
  {
    group: "live in Texas",
    actualPercent: 9,
    userGuessPercent: null,
    guessedPercent: 30,
  },
  {
    group: "are left-handed",
    actualPercent: 11,
    userGuessPercent: null,
    guessedPercent: 34,
  },
  {
    group: "live in California",
    actualPercent: 12,
    userGuessPercent: null,
    guessedPercent: 32,
  },
  {
    group: "are Black",
    actualPercent: 12,
    userGuessPercent: null,
    guessedPercent: 41,
  },
  {
    group: "have an advanced degree",
    actualPercent: 12,
    userGuessPercent: null,
    guessedPercent: 37,
  },
  {
    group: "are first generation immigrants",
    actualPercent: 14,
    userGuessPercent: null,
    guessedPercent: 33,
  },
  {
    group: "are Hispanic",
    actualPercent: 17,
    userGuessPercent: null,
    guessedPercent: 39,
  },
  {
    group: "are Catholic",
    actualPercent: 22,
    userGuessPercent: null,
    guessedPercent: 41,
  },
  {
    group: "own a gun",
    actualPercent: 32,
    userGuessPercent: null,
    guessedPercent: 54,
  },

  {
    group: "have at least a college degree",
    actualPercent: 33,
    userGuessPercent: null,
    guessedPercent: 47,
  },
  {
    group: "have a household income over $100,000",
    actualPercent: 34,
    userGuessPercent: null,
    guessedPercent: 38,
  },
  {
    group: "have a passport",
    actualPercent: 37,
    userGuessPercent: null,
    guessedPercent: 45,
  },

  {
    group: "are obese",
    actualPercent: 42,
    userGuessPercent: null,
    guessedPercent: 56,
  },
  {
    group: "are Republicans",
    actualPercent: 47,
    userGuessPercent: null,
    guessedPercent: 50,
  },
  {
    group: "are married",
    actualPercent: 51,
    userGuessPercent: null,
    guessedPercent: 55,
  },
  {
    group: "have at least one child",
    actualPercent: 57,
    userGuessPercent: null,
    guessedPercent: 58,
  },
  {
    group: "voted in the 2020 election",
    actualPercent: 62,
    userGuessPercent: null,
    guessedPercent: 61,
  },
  {
    group: "have a household income over $50,000",
    actualPercent: 62,
    userGuessPercent: null,
    guessedPercent: 50,
  },
  {
    group: "are white",
    actualPercent: 64,
    userGuessPercent: null,
    guessedPercent: 59,
  },
  {
    group: "own a house",
    actualPercent: 65,
    userGuessPercent: null,
    guessedPercent: 49,
  },
  {
    group: "are fully vaccinated against COVID-19",
    actualPercent: 66,
    userGuessPercent: null,
    guessedPercent: 59,
  },
  {
    group: "have a pet",
    actualPercent: 67,
    userGuessPercent: null,
    guessedPercent: 62,
  },
  {
    group: "are Christian",
    actualPercent: 70,
    userGuessPercent: null,
    guessedPercent: 58,
  },
  {
    group: "have read a book in the past year",
    actualPercent: 77,
    userGuessPercent: null,
    guessedPercent: 50,
  },
  {
    group: "have a household income over $25,000",
    actualPercent: 82,
    userGuessPercent: null,
    guessedPercent: 62,
  },
  {
    group: "have a driver's license",
    actualPercent: 83,
    userGuessPercent: null,
    guessedPercent: 68,
  },
  {
    group: "own a smartphone",
    actualPercent: 85,
    userGuessPercent: null,
    guessedPercent: 76,
  },
  {
    group: "have flown on a plane",
    actualPercent: 88,
    userGuessPercent: null,
    guessedPercent: 59,
  },
  {
    group: "own a car",
    actualPercent: 88,
    userGuessPercent: null,
    guessedPercent: 66,
  },
  {
    group: "have at least a high school degree",
    actualPercent: 89,
    userGuessPercent: null,
    guessedPercent: 65,
  },
];

export default questionList;
